root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/main"  # Linux下无需.exe后缀
# Linux/WSL环境编译命令（移除.exe，指定GOOS=linux确保架构正确）
cmd = "GOOS=linux GOARCH=amd64 go build -o ./tmp/main ."
delay = 1000
exclude_dir = ["assets", "vendor", "docs", "frontend", "client",".idea"]
exclude_file = []
exclude_regex = []
include_ext = ["go", "tpl", "tmpl"]
log = "build-errors.log"
color = true

[misc]
clean_on_exit = true